apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: selenium-grid
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kakliniew/reproduce-selenium-edge-node
    path: selenium-grid
    targetRevision: master
    helm:
      parameters:
        - name: hub.replicaCount
          value: "1"
        - name: chromeNode.enabled
          value: "false"
        - name: firefoxNode.enabled
          value: "false"
        - name: edgeNode.enabled
          value: "true"
        - name: edgeNode.replicaCount
          value: "2"
        - name: hub.image.tag
          value: "4.15.0"
        - name: edgeNode.image.tag
          value: "4.15.0"
        - name: hub.extraEnvironmentVariables[0].name
          value: "SE_JAVA_OPTS"
        - name: hub.extraEnvironmentVariables[0].value
          value: "-XX:+UnlockExperimentalVMOptions -XX:+UseZGC"
        - name: edgeNode.extraEnvironmentVariables[0].name
          value: "SE_JAVA_OPTS"
        - name: edgeNode.extraEnvironmentVariables[0].value
          value: "-XX:+UnlockExperimentalVMOptions -XX:+UseZGC"
  destination:
    server: https://kubernetes.default.svc
    namespace: selenium-grid
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
